apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc 
  labels: 
     name: mysql-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
