apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name: mysql-con
        image: 467336339185.dkr.ecr.us-east-1.amazonaws.com/my_db:v1.0
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        env:
          - name: DBPWD
            value: "pw"
          - name: DBUSER
            value: "root"
          - name: MYSQL_ROOT_PASSWORD
            value: "pw"