apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        -name: mysql-con
        image: 467336339185.dkr.ecr.us-east-1.amazonaws.com/my_db:v1.0
        name: mysql-con
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim