apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
  labels:
    app: employees
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: employees