apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql-pod
spec:
  containers:
  - image: 467336339185.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.0
    name: mysql-con
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    ports:
    - containerPort: 3306