apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 467336339185.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.0
        name: mysql-con
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        ports:
        - containerPort: 3306