apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replica
  labels:
    app: employees
spec:
  selector:
    matchLabels:
      app: employees
  replicas: 3
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - image: 467336339185.dkr.ecr.us-east-1.amazonaws.com/webapp:v2.0
        name: app-con
        env:
        - name: DBHOST
          value:  10.244.0.7
        - name: DBPORT
          value: "3306"  
        - name: DBUSER
          value: root
        - name: DATABASE
          value: employees
        - name: DBPWD
          value: pw
        - name: APP_COLOR
          value: blue  
        ports:
        - containerPort: 8080